server:
  port: 2000

spring:
  # 允许重复的Bean
  main:
    allow-bean-definition-overriding: true
  application:
    name: adrien-mocker
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/adrien_mocker?serverTimezone=Asia/Shanghai&useTimezone=true
    username: root
    password: xdx19710131
    driverClassName: com.mysql.cj.jdbc.Driver

adrien:
  sdk: enable
  script: enable
