server:
  port: 2000

spring:
  # 允许重复的Bean
  main:
    allow-bean-definition-overriding: true
  application:
    name: adrien-ai

ai:
  enable: true
  api-key: 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
